# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ...}: {
  flake.nixosModules.myMachineHardware = { config, lib, pkgs, modulesPath, ... }: {
	  imports = [ 
	      (modulesPath + "/installer/scan/not-detected.nix")
	  ];

	  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
	  boot.initrd.kernelModules = [ ];
	  boot.kernelModules = [ ];
	  boot.extraModulePackages = [ ];

	  fileSystems."/" =
	    { device = "/dev/disk/by-uuid/6a06ee3c-b9bc-4446-bd0c-302a7c249385";
	      fsType = "btrfs";
	    };

	  fileSystems."/home" =
	    { device = "/dev/disk/by-uuid/6a06ee3c-b9bc-4446-bd0c-302a7c249385";
	      fsType = "btrfs";
	      options = [ "subvol=home" ];
	    };

	  fileSystems."/nix" =
	    { device = "/dev/disk/by-uuid/6a06ee3c-b9bc-4446-bd0c-302a7c249385";
	      fsType = "btrfs";
	      options = [ "subvol=nix" ];
	    };

	  fileSystems."/boot" =
	    { device = "/dev/disk/by-uuid/F5C4-40CC";
	      fsType = "vfat";
	      options = [ "fmask=0077" "dmask=0077" ];
	    };

	  swapDevices =
	    [ { device = "/dev/disk/by-uuid/9f8c4758-f9bf-4e78-9267-064f687dab50"; }
	    ];

	  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}

