{ config, lib, ... }:
let
  home = config.home.homeDirectory;
in
{
  # Hyprland is enabled by the NixOS module with UWSM. Home Manager only
  # owns user services and files, avoiding a second compositor lifecycle.
  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };
      listener = [
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 600;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
        {
          timeout = 900;
          on-timeout = "systemctl suspend || loginctl suspend";
        }
      ];
    };
  };

  home.activation.migrateLegacyHyprlandLua = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    stale="$HOME/.config/hypr/hyprland.lua"
    if [ -f "$stale" ] && [ ! -L "$stale" ]; then
      legacy=0
      if grep -Eq 'autogenerated[[:space:]]*=[[:space:]]*true' "$stale"; then
        legacy=1
      fi
      if grep -Fq 'require("hyprland.shell")' "$stale" || grep -Fq "require('hyprland.shell')" "$stale"; then
        legacy=1
      fi
      if grep -Eq '(^|[[:space:]])(source|bind|env|input|general|decoration|windowrule|exec|exec-once)[[:space:]]*=' "$stale"; then
        legacy=1
      fi
      if grep -Eq '\$[A-Za-z_]' "$stale"; then
        legacy=1
      fi
      if [ "$legacy" -eq 1 ]; then
        backup="$HOME/.local/state/nix-conf/backups/hyprland.lua.legacy.$(date +%Y%m%d%H%M%S)"
        $DRY_RUN_CMD mkdir -p "$(dirname "$backup")"
        $DRY_RUN_CMD cp -a "$stale" "$backup"
        $DRY_RUN_CMD rm -f "$stale"
      fi
    fi
  '';

  home.activation.setupScreenshots = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p "${home}/Pictures/Screenshots"
  '';
}
