{ config, lib, pkgs, ... }:
let
  home = config.home.homeDirectory;
  randomWallpaper = pkgs.writeShellScript "end4-wallpaper-random-on-login" ''
    set -eu
    wallpapers_dir="${home}/Pictures/Wallpapers"
    wallpaper="$(${pkgs.findutils}/bin/find "$wallpapers_dir" -type f \
      \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) \
      -print 2>/dev/null | ${pkgs.coreutils}/bin/shuf -n 1)"
    if [ -z "$wallpaper" ]; then
      exit 0
    fi
    ${pkgs.coreutils}/bin/sleep 2
    exec "${home}/.config/quickshell/ii/scripts/colors/switchwall.sh" --image "$wallpaper"
  '';
in
{
  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";
    systemd.enable = false;
    xwayland.enable = true;
  };

  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };
      listener = [
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 600;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
        {
          timeout = 900;
          on-timeout = "systemctl suspend || loginctl suspend";
        }
      ];
    };
  };

  home.activation.migrateLegacyHyprlandLua = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    stale="$HOME/.config/hypr/hyprland.lua"
    if [ -f "$stale" ] && [ ! -L "$stale" ] && grep -Eq 'autogenerated[[:space:]]*=[[:space:]]*true|(^|[[:space:]])(source|bind|env|input|general|decoration|windowrule|exec|exec-once)[[:space:]]*=|\$[A-Za-z_]' "$stale"; then
      backup="$HOME/.local/state/nix-conf/backups/hyprland.lua.hyprlang.$(date +%Y%m%d%H%M%S)"
      $DRY_RUN_CMD mkdir -p "$(dirname "$backup")"
      $DRY_RUN_CMD cp -a "$stale" "$backup"
      $DRY_RUN_CMD rm -f "$stale"
    fi
  '';

  home.activation.setupScreenshots = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p "${home}/Pictures/Screenshots"
  '';

  systemd.user.services.end4-wallpaper-random-on-login = {
    Unit = {
      Description = "Select a random end-4 wallpaper at graphical session start";
      After = [ "graphical-session.target" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = randomWallpaper;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
