#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
HARDWARE_FILE="${REPO_ROOT}/modules/hosts/latitude/hardware.nix"

echo -e "${YELLOW}Generating hardware.nix for Latitude host...${NC}"

# Requisitos
command -v nixos-generate-config >/dev/null 2>&1 || {
  echo -e "${RED}nixos-generate-config is required. Are you on NixOS?${NC}"
  exit 1
}

# Criar um diretório temporário para gerar a configuração
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# O target_root é o ponto de montagem da instalação
TARGET_ROOT="${NIXOS_INSTALL_ROOT:-/}"
if [ -z "${NIXOS_INSTALL_ROOT+x}" ] && [[ "${REPO_ROOT}" == /mnt/* ]]; then
  TARGET_ROOT="/mnt"
fi

echo "Target root: $TARGET_ROOT"

# Gerar configuração de hardware
echo "Running nixos-generate-config..."
nixos-generate-config --root "$TARGET_ROOT" --dir "$TMP_DIR" --show-hardware-config > "$TMP_DIR/hardware-configuration.nix" || {
  echo -e "${RED}Failed to generate hardware configuration.${NC}"
  exit 1
}

# Extrair as partes importantes
echo "Parsing generated hardware configuration..."

# 1. Imports (módulos disponíveis)
INITRD_AVAILABLE=$(grep "boot.initrd.availableKernelModules" "$TMP_DIR/hardware-configuration.nix" || echo 'boot.initrd.availableKernelModules = [ ];')
INITRD_KERNEL=$(grep "boot.initrd.kernelModules" "$TMP_DIR/hardware-configuration.nix" || echo 'boot.initrd.kernelModules = [ ];')
KERNEL_MODULES=$(grep "boot.kernelModules" "$TMP_DIR/hardware-configuration.nix" || echo 'boot.kernelModules = [ ];')
EXTRA_MODULES=$(grep "boot.extraModulePackages" "$TMP_DIR/hardware-configuration.nix" || echo 'boot.extraModulePackages = [ ];')

# 2. FileSystems (substituindo UUIDs por by-partuuid para btrfs se possível, ou apenas usando a saída padrão que já é robusta)
# O nixos-generate-config já lida bem com subvolumes btrfs e partições.
FS_BLOCK=$(awk '/fileSystems\."\/" =/,/swapDevices =/' "$TMP_DIR/hardware-configuration.nix" | sed '$d')

# 3. Plataforma e CPU
HOST_PLATFORM=$(grep "nixpkgs.hostPlatform" "$TMP_DIR/hardware-configuration.nix" || echo 'nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";')
CPU_MICROCODE=$(grep "hardware.cpu.*.updateMicrocode" "$TMP_DIR/hardware-configuration.nix" || echo 'hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;')

# Escrever o novo hardware.nix
cat > "$HARDWARE_FILE" <<EOF
# Do not modify this file!  It was generated by generate-latitude-hardware.sh
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  flake.nixosModules.latitudeHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    $INITRD_AVAILABLE
    $INITRD_KERNEL
    $KERNEL_MODULES
    $EXTRA_MODULES

$FS_BLOCK

    swapDevices = [ ];

    $HOST_PLATFORM
    $CPU_MICROCODE

    hardware.graphics = {
      enable = true;
      enable32Bit = true;
    };
  };
}
EOF

echo -e "${GREEN}Successfully generated ${HARDWARE_FILE}${NC}"
